# Makefile para el programa

# Nombre del programa de salida
TARGET = src/main.py

# Comando all
all:
	python $(TARGET)

# Comando run
run:
	python $(TARGET)

# Comando clean
clean:
	rm -rf __pycache__